version: '3'
services:
  ocrmypdf-watchdog:
    container_name: OCRmyPDF
    network_mode: none
    image: ocrmypdf-watchdog:latest
    restart: always
    environment:
      OCRMYPDF_IN: /in
      OCRMYPDF_OUT: /out
      WATCHDOG_FREQUENCY: 5
      WATCHDOG_EXTENSIONS: pdf,jpg,jpeg,tif,tiff,png,gif
      OCRMYPDF_BINARY: ocrmypdf
      OCRMYPDF_PARAMETER: -l eng+fra+deu --rotate-pages --deskew --jobs 4 --output-type pdfa
    volumes:
    - /home/bernmic/ocrmypdf/in:/in
    - /home/bernmic/ocrmypdf/out:/out
